// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeh-qHevYHP-Dcx_aNXY7afh_tqg918rs',
    appId: '1:817622426760:web:c404ac462a371375e3eb3d',
    messagingSenderId: '817622426760',
    projectId: 'live-score-app-bca6c',
    authDomain: 'live-score-app-bca6c.firebaseapp.com',
    storageBucket: 'live-score-app-bca6c.appspot.com',
    measurementId: 'G-VFELXN57GH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoxr_rQRGQGq02x3X05HVrlWp1JMBQB2w',
    appId: '1:817622426760:android:a94eb2cb1ccad4b9e3eb3d',
    messagingSenderId: '817622426760',
    projectId: 'live-score-app-bca6c',
    storageBucket: 'live-score-app-bca6c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeh-qHevYHP-Dcx_aNXY7afh_tqg918rs',
    appId: '1:817622426760:web:48db19ccd97d89d5e3eb3d',
    messagingSenderId: '817622426760',
    projectId: 'live-score-app-bca6c',
    authDomain: 'live-score-app-bca6c.firebaseapp.com',
    storageBucket: 'live-score-app-bca6c.appspot.com',
    measurementId: 'G-XTMJQJ7F9G',
  );
}
